from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.SimpleHomeRedirectView.as_view(),
        name='home'),
    url(r'^business/$', views.BusinessDetailView.as_view(),
        name='cashup_business_detail'),
    url(r'^business/settings/$', views.BusinessUpdateView.as_view(),
        name='cashup_business_update'),
    url(r'^staff/$',
        views.PersonnelListView.as_view(),
        name='cashup_personnel_list'),
    url(r'^staff/(?P<username>[\w.@+-]+)/closures/$',
        views.PersonnelTillClosureListView.as_view(),
        name='cashup_personnel_closures'),
    url(r'^outlets/$', views.OutletListView.as_view(),
        name='cashup_outlet_list'),
    url(r'^outlets/(?P<name>[\w.@+-]+)/$',
        views.OutletTillClosureListView.as_view(),
        name='cashup_outlet_detail'),
    url(r'^outlets/(?P<name>[\w.@+-]+)/settings/$',
        views.OutletUpdateView.as_view(),
        name='cashup_outlet_settings'),
    url(r'^outlet/new/$',
        views.OutletCreateView.as_view(),
        name='cashup_outlet_create'),
    url(r'^closures/(?P<pk>[0-9]+)/$',
        views.TillClosureDetailView.as_view(),
        name='cashup_closure_detail'),
    url(r'^closures/(?P<pk>[0-9]+)/edit/$',
        views.TillClosureUpdateView.as_view(),
        name='cashup_closure_update'),
    url(r'^outlets/(?P<name>[\w.@+-]+)/close-till/$',
        views.TillClosureCreateView.as_view(),
        name='cashup_closure_create'),
    url(r'^closures/(?P<pk>[0-9]+)/audit-trail/$',
        views.TillClosureAuditTrailListView.as_view(),
        name='cashup_closure_audit_trail_list'),
    url(r'^closures/(?P<pk>[0-9]+)/audit-trail/(?P<version>[0-9]+)/$',
        views.TillClosureAuditTrailDetailView.as_view(),
        name='cashup_closure_audit_trail_detail'),
]
