# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:40
from __future__ import unicode_literals

import cashup.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_time', models.DateTimeField()),
                ('cash_takings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_takings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_takings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note_50GBP', cashup.models.DenominationCountField(default=0, pence_value=1, verbose_name='£50 notes')),
                ('till', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashup.Till')),
            ],
        ),
    ]
