# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0002_auto_20170110_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tillclosure',
            options={'get_latest_by': 'close_time', 'ordering': ['-close_time', 'version_number']},
        ),
        migrations.AlterField(
            model_name='tillclosure',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_tillclosures', to='cashup.Personnel'),
        ),
    ]
