# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0003_auto_20170113_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
