# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0004_auto_20170113_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffPositions',
            new_name='StaffPosition',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name_plural': 'Personnel'},
        ),
    ]
