# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0004_auto_20170102_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tillclosure',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
