# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:16
from __future__ import unicode_literals

import cashup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0005_tillclosure_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='till',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='till', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tillclosure',
            name='close_time',
            field=models.DateTimeField(default=cashup.models.time),
        ),
    ]
