# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models

def populate_is_staff_field(apps, schema_editor):
    StaffPosition = apps.get_model('cashup', 'StaffPosition')
    for sp in StaffPosition.objects.all():
        if not sp.is_manager:
            sp.is_staff = True
            sp.save()

def delete_nonstaff_objects(apps, schema_editor):
    StaffPosition = apps.get_model('cashup', 'StaffPosition')
    for sp in StaffPosition.objects.all():
        if not sp.is_manager and not sp.is_staff:
            sp.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0005_auto_20170115_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffposition',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_is_staff_field, delete_nonstaff_objects),
    ]
