# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 19:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


def populate_outlet_name(apps, schema_editor):
    Outlet = apps.get_model('cashup', 'Outlet')
    for outlet in Outlet.objects.all():
        outlet.name = outlet.slug
        outlet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0006_staffposition_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='slug',
            field=models.SlugField(editable=False, max_length=24),
        ),
        migrations.AddField(
            model_name='outlet',
            name='name',
            field=models.CharField(help_text='Enter a shop name or location', max_length=24, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only letters, numbers and single spaces allowed', regex='^[a-zA-Z0-9]+([ ][a-zA-Z0-9]+)*$')],null=True),
        ),
        migrations.RunPython(populate_outlet_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(help_text='Enter a shop name or location', max_length=24, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only letters, numbers and single spaces allowed', regex='^[a-zA-Z0-9]+([ ][a-zA-Z0-9]+)*$')]),
        ),
    ]
