# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0006_auto_20170105_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='till',
            name='default_float',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
