# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0007_till_default_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='tillclosure',
            name='closed_by',
            field=models.CharField(default='Unknown', help_text='Staff name/initials', max_length=20),
            preserve_default=False,
        ),
    ]
