# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0008_tillclosure_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tillclosure',
            name='notes',
            field=models.TextField(blank=True, help_text='Add any useful info here'),
        ),
    ]
