# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:19
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0009_auto_20170105_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tillclosure',
            name='card_takings',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tillclosure',
            name='cash_takings',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
