# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0012_auto_20170107_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='till',
            name='outlet_name',
            field=models.CharField(max_length=128, verbose_name='Outlet'),
        ),
    ]
