# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0014_auto_20170107_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to=settings.AUTH_USER_MODEL),
        ),
    ]
