# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0015_auto_20170107_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='outlet_name',
            new_name='name',
        ),
    ]
