# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0017_auto_20170107_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tillclosure',
            old_name='till',
            new_name='outlet',
        ),
    ]
