# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:45
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashup', '0018_auto_20170107_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tillclosure',
            options={'get_latest_by': 'close_time', 'ordering': ['close_time']},
        ),
        migrations.AlterField(
            model_name='outlet',
            name='default_float',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.SlugField(help_text='Enter a shop name or location', max_length=128),
        ),
        migrations.AlterField(
            model_name='tillclosure',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tillclosures', to='cashup.Outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together=set([('name', 'user')]),
        ),
    ]
