# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashup', '0021_auto_20170108_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='staff',
            field=models.ManyToManyField(related_name='workplaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
