# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Business = apps.get_model('cashup', 'Business')
    User = apps.get_registered_model('auth', 'User')
    for u in User.objects.all():
        if u.outlets.exists():
            b = Business(name=u.username)
            b.user = u
            b.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashup', '0022_outlet_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=12)),
                ('staff', models.ManyToManyField(editable=False, related_name='employers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
