# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Business = apps.get_model('cashup', 'Business')
    Outlet = apps.get_model('cashup', 'Outlet')
    for o in Outlet.objects.all():
        b = o.user.business
        o.business = b
        o.save()

def reverse_func(apps, schema_editor):
    Outlet = apps.get_model('cashup', 'Outlet')
    for o in Outlet.objects.all():
        o.user = b.user
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0023_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='business',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='outlets', to='Business', null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='outlet',
            name='business',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='outlets', to='Business'),
        ),
    ]
