# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0024_auto_20170108_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together=set([('name', 'business')]),
        ),
    ]
