# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0025_auto_20170108_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='user',
        ),
    ]
