# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0026_remove_outlet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.SlugField(help_text='Enter a shop name or location', max_length=24),
        ),
    ]
