# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0028_remove_business_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='staff',
            new_name='_staff',
        ),
    ]
