# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



def forwards_func(apps, schema_editor):
    Outlet = apps.get_model('cashup', 'Outlet')
    OutletStaff = apps.get_model('cashup', 'OutletStaff')
    for o in Outlet.objects.all():
        for u in o._staff.all():
            manager = hasattr(u, 'business')
            OutletStaff.objects.create(user=u, outlet=o, is_manager=manager)

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashup', '0029_auto_20170108_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='outlet',
            name='_staff',
            field=models.ManyToManyField(related_name='_workplaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outletstaff',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashup.Outlet'),
        ),
        migrations.AddField(
            model_name='outletstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outlet',
            name='staff',
            field=models.ManyToManyField(related_name='workplaces', through='cashup.OutletStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
