# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashup', '0031_remove_outlet__staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outletstaff',
            unique_together=set([('outlet', 'user')]),
        ),
    ]
