# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0032_auto_20170108_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesHelpText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
